name: CI
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  analises_estaticas:
    name: Análises Estáticas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.2', '7.3', '7.4', '8.0', '8.1']
      fail-fast: false

    steps:
      - name: Setando PHP com soap e mbstring
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, soap

      - name: checkout
        uses: actions/checkout@v2

      - name: Instalando dependências PHP 7.2
        if: matrix.php-version == '7.2'
        run: |
          composer require 'phpunit/phpunit:^7.0' -W --dev
          composer install --no-progress -o --no-ansi --no-interaction

      - name: Instalando dependências
        if: matrix.php-version != '7.2'
        run: |
          composer require 'phpunit/phpunit:^8.0' -W --dev
          composer install --no-progress -o --no-ansi --no-interaction

      - name: PHPStan
        run: |
          composer stan

      - name: PHPUnit
        run: |
          composer test

      
